"""SLSA provenance checker — assess Supply-chain Levels for Software Artifacts."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from ossguard.detector import ProjectInfo, detect_project


@dataclass
class SLSARequirement:
    """A single SLSA requirement."""

    id: str
    level: int
    description: str
    status: str = "unknown"  # "met", "unmet", "unknown"
    evidence: str = ""
    recommendation: str = ""


@dataclass
class SLSAReport:
    """SLSA assessment report."""

    requirements: list[SLSARequirement] = field(default_factory=list)
    achieved_level: int = 0  # 0-4
    met_count: int = 0
    total_count: int = 0

    @property
    def level_label(self) -> str:
        if self.achieved_level == 0:
            return "SLSA Level 0 (No provenance)"
        return f"SLSA Build Level {self.achieved_level}"


# SLSA Build Levels requirements
_REQUIREMENTS: list[tuple[str, int, str]] = [
    # Level 1 — Provenance exists
    (
        "slsa-l1-provenance",
        1,
        "Build process MUST generate provenance describing how the artifact was built",
    ),
    ("slsa-l1-ci", 1, "Build MUST run in a CI/CD system (not a developer workstation)"),
    ("slsa-l1-published", 1, "Provenance MUST be available to consumers"),
    # Level 2 — Hosted build, signed provenance
    ("slsa-l2-hosted", 2, "Build MUST run on a hosted build service"),
    ("slsa-l2-signed", 2, "Provenance MUST be signed (authenticated)"),
    ("slsa-l2-service-gen", 2, "Provenance MUST be generated by the build service itself"),
    # Level 3 — Hardened builds
    ("slsa-l3-isolated", 3, "Build MUST run in an isolated, ephemeral environment"),
    ("slsa-l3-unforgeable", 3, "Provenance MUST be unforgeable (can't be modified by build job)"),
    ("slsa-l3-non-falsifiable", 3, "Build service MUST guarantee non-falsifiable provenance"),
    # Level 4 — Two-party review + hermetic
    ("slsa-l4-hermetic", 4, "Build MUST be hermetic (no network access during build)"),
    ("slsa-l4-reproducible", 4, "Build SHOULD be reproducible"),
    ("slsa-l4-two-party", 4, "All changes require two-party review before merging"),
]


def check_slsa(project_path: str | Path) -> SLSAReport:
    """Assess a project's SLSA build level.

    Args:
        project_path: Path to the project.

    Returns:
        SLSAReport with level assessment.
    """
    path = Path(project_path).resolve()
    info = detect_project(path)

    requirements: list[SLSARequirement] = []

    for req_id, level, description in _REQUIREMENTS:
        status, evidence, rec = _check_requirement(req_id, info, path)
        requirements.append(
            SLSARequirement(
                id=req_id,
                level=level,
                description=description,
                status=status,
                evidence=evidence,
                recommendation=rec,
            )
        )

    met = sum(1 for r in requirements if r.status == "met")

    # Calculate achieved level
    achieved = 0
    for lvl in range(1, 5):
        lvl_reqs = [r for r in requirements if r.level == lvl]
        if lvl_reqs and all(r.status == "met" for r in lvl_reqs):
            achieved = lvl
        else:
            break

    return SLSAReport(
        requirements=requirements,
        achieved_level=achieved,
        met_count=met,
        total_count=len(requirements),
    )


def _check_requirement(req_id: str, info: ProjectInfo, path: Path) -> tuple[str, str, str]:
    """Check a single SLSA requirement."""

    wf_dir = path / ".github" / "workflows"
    has_workflows = wf_dir.is_dir()

    # Level 1
    if req_id == "slsa-l1-provenance":
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if any(kw in content for kw in ["provenance", "slsa", "attest", "in-toto"]):
                        return "met", f"Provenance generation found in {wf.name}", ""
        return (
            "unmet",
            "",
            "Add SLSA provenance generation (e.g. slsa-framework/slsa-github-generator)",
        )

    if req_id == "slsa-l1-ci":
        if info.has_github_actions:
            return "met", "GitHub Actions CI found", ""
        for ci in [".travis.yml", ".circleci/config.yml", "Jenkinsfile", ".gitlab-ci.yml"]:
            if (path / ci).exists():
                return "met", f"CI found: {ci}", ""
        return "unmet", "", "Set up CI/CD — run `ossguard ci`"

    if req_id == "slsa-l1-published":
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if "upload-artifact" in content or "release" in content:
                        return "met", "Artifacts published in CI", ""
        return "unknown", "", "Publish provenance alongside release artifacts"

    # Level 2
    if req_id == "slsa-l2-hosted":
        if info.has_github_actions:
            return "met", "GitHub Actions is a hosted build service", ""
        return "unknown", "", "Use a hosted CI service (GitHub Actions, Cloud Build, etc.)"

    if req_id == "slsa-l2-signed":
        if info.has_sigstore:
            return "met", "Sigstore signing configured", ""
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if any(kw in content for kw in ["cosign", "sigstore", "sign", "attest"]):
                        return "met", f"Signing found in {wf.name}", ""
        return "unmet", "", "Sign provenance with Sigstore — run `ossguard init`"

    if req_id == "slsa-l2-service-gen":
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if "slsa-github-generator" in content or "slsa-framework" in content:
                        return "met", "SLSA generator produces provenance", ""
        return (
            "unmet",
            "",
            "Use slsa-framework/slsa-github-generator for service-generated provenance",
        )

    # Level 3
    if req_id == "slsa-l3-isolated":
        if info.has_github_actions:
            # GitHub Actions uses ephemeral VMs by default
            return "met", "GitHub Actions runs on ephemeral VMs", ""
        return "unknown", "", "Ensure builds run in isolated, ephemeral environments"

    if req_id == "slsa-l3-unforgeable":
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if "slsa-github-generator" in content:
                        return "met", "SLSA generator produces unforgeable provenance", ""
        return "unmet", "", "Use SLSA generator for unforgeable provenance"

    if req_id == "slsa-l3-non-falsifiable":
        if has_workflows:
            for wf in wf_dir.iterdir():
                if wf.suffix in (".yml", ".yaml"):
                    content = wf.read_text().lower()
                    if "slsa-github-generator" in content:
                        return "met", "SLSA generator guarantees non-falsifiable provenance", ""
        return "unmet", "", "Ensure provenance is generated outside the build job"

    # Level 4
    if req_id == "slsa-l4-hermetic":
        return "unknown", "", "Verify builds are hermetic (no network access during build)"

    if req_id == "slsa-l4-reproducible":
        return "unknown", "", "Verify builds are reproducible"

    if req_id == "slsa-l4-two-party":
        bp = path / "BRANCH_PROTECTION.md"
        if bp.exists():
            content = bp.read_text().lower()
            if "review" in content and ("2" in content or "two" in content):
                return "met", "Two-party review documented", ""
        return "unknown", "", "Require two-party review for all changes"

    return "unknown", "", ""
